# Generated by Django 3.2.20 on 2023-08-02 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intaian', '0002_modelrwgolongan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPasangan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idsiasn', models.TextField(blank=True, null=True)),
                ('ayahid', models.TextField(blank=True, db_column='ayahId', null=True)),
                ('ibuid', models.TextField(blank=True, db_column='ibuId', null=True)),
                ('nama', models.TextField(blank=True, null=True)),
                ('namaktp', models.TextField(blank=True, db_column='namaKtp', null=True)),
                ('gelardepan', models.TextField(blank=True, db_column='gelarDepan', null=True)),
                ('gelarblk', models.TextField(blank=True, db_column='gelarBlk', null=True)),
                ('tempatlahir', models.TextField(blank=True, db_column='tempatLahir', null=True)),
                ('tgllahir', models.TextField(blank=True, db_column='tglLahir', null=True)),
                ('aktameninggal', models.TextField(blank=True, db_column='aktaMeninggal', null=True)),
                ('tglmeninggal', models.TextField(blank=True, db_column='tglMeninggal', null=True)),
                ('jeniskelamin', models.TextField(blank=True, db_column='jenisKelamin', null=True)),
                ('jenisanak', models.TextField(blank=True, db_column='jenisAnak', null=True)),
                ('statushidup', models.TextField(blank=True, db_column='StatusHidup', null=True)),
                ('jeniskawinid', models.IntegerField(blank=True, db_column='JenisKawinId', null=True)),
                ('statusnikah', models.TextField(blank=True, db_column='statusNikah', null=True)),
                ('datapernikahan_id', models.TextField(blank=True, db_column='dataPernikahan_id', null=True)),
                ('datapernikahan_orangid', models.TextField(blank=True, db_column='dataPernikahan_orangId', null=True)),
                ('datapernikahan_pnsorangid', models.TextField(blank=True, db_column='datapernikahan_pnsorangid', null=True)),
                ('datapernikahan_tgglmenikah', models.TextField(blank=True, db_column='dataPernikahan_tgglMenikah', null=True)),
                ('datapernikahan_aktamenikah', models.TextField(blank=True, db_column='dataPernikahan_aktaMenikah', null=True)),
                ('datapernikahan_tgglcerai', models.TextField(blank=True, db_column='dataPernikahan_tgglCerai', null=True)),
                ('datapernikahan_aktacerai', models.TextField(blank=True, db_column='dataPernikahan_aktaCerai', null=True)),
                ('datapernikahan_posisi', models.IntegerField(blank=True, db_column='dataPernikahan_posisi', null=True)),
                ('datapernikahan_status', models.IntegerField(blank=True, db_column='dataPernikahan_status', null=True)),
                ('datapernikahan_ispns', models.TextField(blank=True, db_column='dataPernikahan_isPns', null=True)),
                ('datapernikahan_noskpensiun', models.TextField(blank=True, db_column='dataPernikahan_noSkPensiun', null=True)),
            ],
            options={
                'db_table': 'Pasangan',
                'managed': False,
            },
        ),
    ]
