# Generated by Django 3.2.20 on 2023-08-07 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intaian', '0004_rwpendidikan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRwPendidikan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idsiasn', models.TextField(blank=True, db_column='idsiasn', null=True)),
                ('nipbaru', models.TextField(blank=True, db_column='nipBaru', null=True)),
                ('niplama', models.TextField(blank=True, db_column='nipLama', null=True)),
                ('pendidikanid', models.TextField(blank=True, db_column='pendidikanId', null=True)),
                ('pendidikannama', models.TextField(blank=True, db_column='pendidikanNama', null=True)),
                ('tkpendidikanid', models.IntegerField(blank=True, db_column='tkPendidikanId', null=True)),
                ('tkpendidikannama', models.TextField(blank=True, db_column='tkPendidikanNama', null=True)),
                ('tahunlulus', models.IntegerField(blank=True, db_column='tahunLulus', null=True)),
                ('tgllulus', models.TextField(blank=True, db_column='tglLulus', null=True)),
                ('ispendidikanpertama', models.IntegerField(blank=True, db_column='isPendidikanPertama', null=True)),
                ('nomorijasah', models.TextField(blank=True, db_column='nomorIjasah', null=True)),
                ('namasekolah', models.TextField(blank=True, db_column='namaSekolah', null=True)),
                ('gelardepan', models.TextField(blank=True, db_column='gelarDepan', null=True)),
                ('gelarbelakang', models.TextField(blank=True, db_column='gelarBelakang', null=True)),
                ('path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RwPendidikan',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='RwPendidikan',
        ),
    ]
